language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run coverage
  - npm run build
after_success:
  - npm run coverage:report
